version: '3.8'

services:
  server:
    image: "docker.io/jollyboss/tcg_my-server"
    container_name: "tcg_my_container"
    environment:
      - "API_HOST=0.0.0.0"
      - "API_PORT=8080"
      - "CORS_ALLOWED_ORIGINS=http://localhost:3000"
      - "CORS_ALLOW_CREDENTIALS=true"
      - "CORS_ALLOW_PRIVATE_NETWORK=false"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
      - "REDIS_NAME=0"
      - "REDIS_CACHE_TIME=5m"
      - "REDIS_ENABLE=true"
      - "RATE_KEY=****" #replace with your API key
      - "RATE_ENDPOINT=http://api.exchangeratesapi.io/v1/latest"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}

  redis:
    image: 'redis:7.2'
    restart: always
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
