version: '3.8'

services:
  server:
    image: "docker.io/jollyboss/tcg_my-server"
    container_name: "tcg_my_container"
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}

  redis:
    image: 'redis:7.2'
    restart: always
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
