// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Card struct {
	Code      string  `json:"code"`
	Name      string  `json:"name"`
	Rarity    string  `json:"rarity"`
	Condition *string `json:"condition,omitempty"`
	Price     int     `json:"price"`
	Source    string  `json:"source"`
}
